/* eslint-disable */
// This file is auto-generated by react-native-bedrock. DO NOT EDIT.
import { Route as _DetailRoute } from '../pages/detail';
import { Route as _IndexRoute } from '../pages/';

declare module 'react-native-bedrock' {
  interface RegisterScreen {
    '/detail': ReturnType<typeof _DetailRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
  }
}
